#!/usr/local/bin/perl
# $Id$
#
# Monitor disk space usage. Susan Feng (sfeng@stanford.edu)
#
# Arguments are:
#
# host [host...] 
#
# This script will exit with value 1 if the partions on "host" is above 85%
# full. 
#
# The first output line is a list of the hosts which failed, and
# how much space is free, in kbytes.
#

use Getopt::Std;
use English;

getopts ("c:");
getopts ("w:");
getopts ("H:");
$WARNING= $opt_c || 85;
$CRITICAL= $opt_w || 90;
$h = $opt_H;
 
my $voscmd="/usr/local/bin/vos partinfo";
my @failures=();
my ($part, $used, $free, $total, $percent);

@infos=();
@infos=`$voscmd $h 2> /dev/null`;
foreach $l (@infos) {
    ($part,$free,$total) = (split(/\s+/,$l))[4,5,11];
     $used=$total-$free;
     $percent=int (($used/$total)*100);
     if ($percent >= $CRITICAL) {
         push (@critical, "$h: $part $percent% full, free $free\n");
     }
     elsif ($percent >= $WARNING) {
         push (@warning, "$h: $part $percent% full, free $free\n");
     }
}

if (@critical) {
    print @critical;
    exit 2;
}
if (@warning) {
   print @warning;
   exit 1;
}
print "@infos\n";
exit 0;
