#!/usr/local/bin/perl
# $Id$
#
# Monitor disk space usage. Susan Feng (sfeng@stanford.edu)
#
# Arguments are:
#
# host [host...] 
#
# This script will exit with value 1 if the partions on "host" is above 85%
# full. 
#
# The first output line is a list of the hosts which failed, and
# how much space is free, in kbytes.
#

use Getopt::Std;
use English;

%options=();
getopts ("c:w:H:", \%options);

$WARNINGS = $options{w} || 85;
$CRITICAL = $options{c} || 90;
$h = $options{H};

if ($WARNINGS > $CRITICAL) {
  print "Warning amount cannot be greater than Critical amount.\n";
  exit 0;
}
 
my $voscmd="/usr/local/bin/vos partinfo";
my @failures=();
my ($part, $used, $free, $total, $percent);

@infos=();
@infos=`$voscmd $h 2> /dev/null`;

foreach $l (@infos) {
    ($part,$free,$total) = (split(/\s+/,$l))[4,5,11];
     $used=$total-$free;
     $percent=int (($used/$total)*100);
     if ($percent >= $CRITICAL) {
         push (@critical, "$h: $part $percent% full, free $free\n");
     }
     elsif ($percent >= $WARNINGS) {
         push (@warnings, "$h: $part $percent% full, free $free\n");
     }
    push (@final, "$part$percent%"); 
    
}

if (@critical) {
    print @critical;
    exit 2;
}
if (@warning) {
   print @warning;
   exit 1;
}
foreach $l (@final) {
   chomp($l);
   print "$l ";
}
print "\n";
exit 0;
