#!/usr/local/bin/perl
# $Id$

use Getopt::Std;

getopts ("H:");
$server = $opt_H;

$rxdebug = '/usr/local/bin/rxdebug';
@failures=();
$hiWaterMark=8;

# Get the output of rxdebug $server.
open(RXDEBUG, "$rxdebug $server |")
  || die("Can't open rxdebug\n");
$blocked{$server} = 0;
while (<RXDEBUG>) {
    if ( /waiting_for_process/ ) {
      $blocked{$server}++;
    }
}
close(RXDEBUG);

foreach $server (sort keys %blocked) {
   $blocked=$blocked{$server};
   if ($blocked >= $hiWaterMark) {
     push (@failures, "$server blck: $blocked");
   }
}

if (@failures == 0) {
    print "rxdebug OK\n";
    exit 0;
}

print "@failures\n";
exit 2;
